import { defineCollection, z } from 'astro:content';

/**
 * Nucleus Commerce — Content Collections Schema
 * 
 * Works: Artist portfolio pieces (audio, physical, digital, collaborations)
 * Products: Shop items for sale
 */

// Image variant schema (auto-generated by media processor)
const imageVariantSchema = z.object({
  url: z.string(),
  width: z.number(),
  height: z.number(),
  size: z.number(), // bytes
});

const imageVariantsSchema = z.record(
  z.string(), // format: webp, avif
  z.record(z.string(), imageVariantSchema) // size: sm, md, lg, xl
);

// Media item schema (used by both works and products)
const mediaItemSchema = z.discriminatedUnion('type', [
  // Image media
  z.object({
    type: z.literal('image'),
    src: z.string(), // Primary/legacy URL
    variants: imageVariantsSchema.optional(),
    blurhash: z.string().optional(),
    dominantColor: z.string().optional(),
    width: z.number(),
    height: z.number(),
    alt: z.string(),
    caption: z.string().optional(),
  }),
  // Audio media
  z.object({
    type: z.literal('audio'),
    src: z.string(),
    variants: z.record(z.string(), z.object({
      url: z.string(),
      duration: z.number(),
      size: z.number(),
    })).optional(),
    waveform: z.string().optional(), // URL to waveform JSON
    title: z.string(),
    duration: z.number().optional(), // seconds
    caption: z.string().optional(),
  }),
  // Video media
  z.object({
    type: z.literal('video'),
    src: z.string(),
    poster: z.string().optional(),
    variants: z.record(z.string(), z.object({
      url: z.string(),
      quality: z.string(),
    })).optional(),
    width: z.number().optional(),
    height: z.number().optional(),
    caption: z.string().optional(),
  }),
  // External embed (YouTube, Vimeo, SoundCloud, etc.)
  z.object({
    type: z.literal('embed'),
    src: z.string(), // Embed URL
    provider: z.enum(['youtube', 'vimeo', 'soundcloud', 'bandcamp', 'other']),
    width: z.number().optional(),
    height: z.number().optional(),
    caption: z.string().optional(),
  }),
]);

// Works collection — Artist portfolio pieces
const worksCollection = defineCollection({
  type: 'content',
  schema: z.object({
    // Core metadata
    title: z.string(),
    slug: z.string(),
    category: z.enum(['audio', 'physical', 'digital', 'collaborations']),
    
    // Dates
    date: z.date(),
    endDate: z.date().optional(), // For exhibitions, projects
    
    // Display
    featured: z.boolean().default(false),
    coverImage: z.string().optional(), // Reference to media id
    
    // Media gallery
    media: z.array(mediaItemSchema).default([]),
    
    // Taxonomy
    tags: z.array(z.string()).default([]),
    materials: z.array(z.string()).optional(), // For physical works
    dimensions: z.object({
      width: z.number().optional(),
      height: z.number().optional(),
      depth: z.number().optional(),
      unit: z.enum(['in', 'cm', 'ft', 'm']).default('in'),
    }).optional(),
    
    // Relationships
    relatedWorks: z.array(z.string()).default([]),
    collaborators: z.array(z.object({
      name: z.string(),
      role: z.string().optional(),
      url: z.string().optional(),
    })).optional(),
    
    // Commerce integration
    forSale: z.boolean().default(false),
    price: z.number().optional(),
    productId: z.string().optional(), // Links to product collection
    edition: z.object({
      total: z.number(),
      available: z.number(),
    }).optional(),
    
    // SEO
    description: z.string().optional(),
    ogImage: z.string().optional(),
  }),
});

// Products collection — Shop items
const productsCollection = defineCollection({
  type: 'data',
  schema: z.object({
    name: z.string(),
    slug: z.string(),
    
    // Pricing
    price: z.number(), // in cents (or dollars, be consistent)
    currency: z.string().default('USD'),
    compareAtPrice: z.number().optional(), // Original price for sales
    
    // Content
    description: z.string(),
    shortDescription: z.string().optional(),
    
    // Media
    images: z.array(z.object({
      src: z.string(),
      variants: imageVariantsSchema.optional(),
      blurhash: z.string().optional(),
      alt: z.string(),
      isPrimary: z.boolean().default(false),
      sortOrder: z.number().default(0),
    })),
    
    // Inventory
    inventory: z.object({
      trackQuantity: z.boolean().default(true),
      quantity: z.number().default(0),
      allowBackorders: z.boolean().default(false),
    }),
    
    // Variants (size, color, etc.)
    variants: z.array(z.object({
      name: z.string(), // "Size", "Color"
      options: z.array(z.object({
        value: z.string(), // "Large", "Red"
        priceModifier: z.number().default(0),
        sku: z.string().optional(),
        inventory: z.number().optional(),
      })),
    })).optional(),
    
    // Organization
    categories: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    
    // Shipping
    requiresShipping: z.boolean().default(true),
    weight: z.object({
      value: z.number(),
      unit: z.enum(['g', 'kg', 'oz', 'lb']),
    }).optional(),
    
    // Payment
    stripePriceId: z.string().optional(),
    stripeProductId: z.string().optional(),
    
    // Status
    status: z.enum(['draft', 'active', 'archived']).default('draft'),
    
    // SEO
    metaDescription: z.string().optional(),
    ogImage: z.string().optional(),
    
    // Timestamps
    createdAt: z.date().default(() => new Date()),
    updatedAt: z.date().default(() => new Date()),
  }),
});

// Pages collection — CMS-style pages (about, contact, etc.)
const pagesCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    description: z.string().optional(),
    layout: z.enum(['default', 'fullwidth', 'minimal']).default('default'),
    showInNav: z.boolean().default(false),
    navOrder: z.number().optional(),
    ogImage: z.string().optional(),
  }),
});

export const collections = {
  works: worksCollection,
  products: productsCollection,
  pages: pagesCollection,
};
